// internal/oidentd/oidentd.go

package oidentd

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"strings"
	"text/template"
	"time"

	"github.com/kofany/gNb/internal/config"
	"github.com/kofany/gNb/internal/util"
)

const oidentdConfigPath = "/etc/oidentd.conf"
const configTemplate = `# This is the system-wide configuration file for oidentd.
# Generated by PT-gNb Bot on: {{ .Timestamp }}
# See oidentd.conf(5) for more information.
default {
    default {
        deny spoof
        deny spoof_all
        deny spoof_privport
        allow random
        allow random_numeric
        deny numeric
        deny hide
        deny forward
    }
}
user {{ .Username }} {
    default {
        force reply {{ .Idents }}
    }
}
`

type ConfigData struct {
	Timestamp string
	Username  string
	Idents    string
}

// currentUsername returns the username under which the bot will run.
// In sudo mode the binary itself still runs as the invoking user, and
// oidentd matches connection ownership by UID — so we always want the
// real (effective) user, not "root" just because we're using sudo.
func currentUsername() (string, error) {
	u, err := user.Current()
	if err != nil {
		return "", fmt.Errorf("failed to resolve current user: %v", err)
	}
	if u.Username == "" {
		return "", fmt.Errorf("current user has empty username")
	}
	return u.Username, nil
}

type runMode int

const (
	modeDirect runMode = iota // running as root, write/restart directly
	modeSudo                  // non-root with passwordless sudo
)

// HasPasswordlessSudo reports whether the current user can invoke sudo
// without being prompted for a password. Probed via `sudo -n true`.
func HasPasswordlessSudo() bool {
	return exec.Command("sudo", "-n", "true").Run() == nil
}

// SetupOidentd konfiguruje oidentd. Działa gdy program jest root,
// albo gdy bieżący użytkownik ma passwordless sudo — wtedy zapisy do
// /etc/oidentd.conf i restart usługi idą przez `sudo -n`.
func SetupOidentd(cfg *config.Config) error {
	var mode runMode
	switch {
	case os.Geteuid() == 0:
		mode = modeDirect
	case HasPasswordlessSudo():
		mode = modeSudo
	default:
		return fmt.Errorf("oidentd setup requires root or passwordless sudo")
	}

	if !isDebianSystem() {
		return fmt.Errorf("oidentd setup requires Debian-based system")
	}

	requiredIdents := len(cfg.Bots) + 10

	idents, err := generateIdents(requiredIdents)
	if err != nil {
		return fmt.Errorf("failed to generate idents: %v", err)
	}

	if err := updateOidentdConfig(idents, mode); err != nil {
		return fmt.Errorf("failed to update oidentd config: %v", err)
	}

	if err := restartOidentd(mode); err != nil {
		return fmt.Errorf("failed to restart oidentd: %v", err)
	}

	util.Info("Oidentd configured successfully with %d idents (mode=%s)", len(idents), modeName(mode))
	return nil
}

func modeName(m runMode) string {
	if m == modeSudo {
		return "sudo"
	}
	return "direct"
}

func isDebianSystem() bool {
	_, err := os.Stat("/etc/debian_version")
	return err == nil
}

// internal/oidentd/oidentd.go

func generateIdents(count int) ([]string, error) {
	// Wczytaj słowa z pliku gob
	source, err := util.LoadWordsFromGob("data/words.gob")
	if err != nil {
		return nil, fmt.Errorf("failed to load words from gob: %v", err)
	}

	// Pobierz większą ilość słów do filtrowania
	words, err := source.GetRandomWords(count * 3) // pobieramy 3x więcej słów do filtrowania
	if err != nil {
		return nil, fmt.Errorf("failed to get random words: %v", err)
	}

	// Filtruj i wybierz odpowiednie słowa
	var validWords []string
	for _, word := range words {
		word = strings.ToLower(word)
		if len(word) >= 3 && len(word) <= 9 && isValidIdent(word) {
			validWords = append(validWords, word)
		}
		if len(validWords) >= count {
			break
		}
	}

	if len(validWords) < count {
		return nil, fmt.Errorf("not enough valid words found: got %d, need %d", len(validWords), count)
	}

	// Używamy tylko potrzebnej liczby słów
	validWords = validWords[:count]

	// Dodaj cudzysłowy do identów
	idents := make([]string, len(validWords))
	for i, word := range validWords {
		idents[i] = `"` + word + `"`
	}

	return idents, nil
}

func isValidIdent(word string) bool {
	if len(word) == 0 || !isLetter(rune(word[0])) {
		return false
	}
	for _, r := range word {
		if !isLetter(r) && !isNumber(r) {
			return false
		}
	}
	return true
}

func isLetter(r rune) bool {
	return (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')
}

func isNumber(r rune) bool {
	return r >= '0' && r <= '9'
}

func updateOidentdConfig(idents []string, mode runMode) error {
	tmpl, err := template.New("oidentd").Parse(configTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %v", err)
	}

	username, err := currentUsername()
	if err != nil {
		return err
	}

	data := ConfigData{
		Timestamp: time.Now().Format("2006-01-02 15:04:05"),
		Username:  username,
		Idents:    strings.Join(idents, " "),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("failed to execute template: %v", err)
	}

	if mode == modeDirect {
		if err := os.WriteFile(oidentdConfigPath, buf.Bytes(), 0644); err != nil {
			return fmt.Errorf("failed to write config file: %v", err)
		}
		return nil
	}

	tmp, err := os.CreateTemp("", "gnb-oidentd-*.conf")
	if err != nil {
		return fmt.Errorf("failed to create temp file: %v", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if _, err := tmp.Write(buf.Bytes()); err != nil {
		tmp.Close()
		return fmt.Errorf("failed to write temp file: %v", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("failed to close temp file: %v", err)
	}

	cmd := exec.Command("sudo", "-n", "install", "-m", "0644", "-o", "root", "-g", "root", tmpPath, oidentdConfigPath)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("sudo install failed: %v: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

func restartOidentd(mode runMode) error {
	var cmd *exec.Cmd
	if mode == modeDirect {
		cmd = exec.Command("systemctl", "restart", "oidentd.service")
	} else {
		cmd = exec.Command("sudo", "-n", "systemctl", "restart", "oidentd.service")
	}
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to restart oidentd service: %v: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}
