global:
  log_level: debug  # Poziom logowania: debug, info, warning, error
  ison_interval: 1  # Interval w sekundach między zapytaniami ISON
  nick_api:
    url: 'https://i.got.al/words.php'
    max_word_length: 12
    timeout: 5  # Timeout dla zapytań do API w sekundach
  max_nick_length: 14
  owner_command_prefixes:
    - "!"
    - "."
    - "@"
  reconnect_retries: 3
  reconnect_interval: 2

bots:
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 192.168.176.33
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:8c2:9b0c:ec8b:eb2e 
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 192.168.176.33
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:8c2:9b0c:ec8b:eb2e 
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 192.168.176.33
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:8c2:9b0c:ec8b:eb2e 
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 192.168.176.33
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:8c2:9b0c:ec8b:eb2e 

channels:
  - "#irpg"

owner_command_prefixes:
  - "!"
  - "."
  - "@"