global:
  log_level: debug  # Logging level: debug, info, warning, error
  ison_interval: 1  # Interval in seconds between ISON requests
  nick_api:
    url: 'https://i.got.al/words.php'
    max_word_length: 12
    timeout: 5  # Timeout for API requests in seconds
  max_nick_length: 14
  owner_command_prefixes:
    - "!"
    - "."
    - "@"
  reconnect_retries: 3
  reconnect_interval: 2

bots:
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 192.168.176.35
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1c56:2b73:771e:f9dd

channels:
  - "#irpg"

owner_command_prefixes:
  - "!"
  - "."
  - "@"
