global: # Please do not play with global values if you are not sure what you are doing
  log_level: warning  # Logging level: debug, info, warning, error
  ison_interval: 1  # Interval in seconds between ISON requests
  nick_api:
    url: 'https://i.got.al/words.php'
    max_word_length: 12
    timeout: 5  # Timeout for API requests in seconds
  max_nick_length: 14
  owner_command_prefixes:
    - "!"
    - "."
    - "@"
  reconnect_retries: 3
  reconnect_interval: 2
  mass_command_cooldown: 5
  
bots:
  - server: irc.al #example server 
    port: 6667
    ssl: false
    vhost: 192.168.176.35 # example IPv4
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1111:1111:1111:1111 # example IPv6 
  - server: irc.al #example server 
    port: 6667
    ssl: false
    vhost: 192.168.176.35 # example IPv4
  - server: mirc.irc.al
    port: 6667
    ssl: false
    vhost: 2a02:2454:8545:4900:1111:1111:1111:1111 # example IPv6 

channels:
  - "#irc.al" #example channel

owner_command_prefixes:
  - "!"
  - "."
  - "@"
  